// <auto-generated />
using System;
using Cigars.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cigars.Migrations
{
    [DbContext(typeof(CigarDataContext))]
    [Migration("20240412183744_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.18");

            modelBuilder.Entity("Cigars.Data.Cigar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Binder")
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .HasColumnType("TEXT");

                    b.Property<string>("Filler")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("Wrapper")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("cigar_set", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Binder = "Nicuraguan",
                            Body = "Full",
                            Brand = "Drew Estate",
                            Filler = "Nicuraguan",
                            Name = "Liga Privada No. 9",
                            Origin = "Nicuraguan",
                            Price = 23.989999999999998,
                            Wrapper = "Maduro Nicuraguan"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
