// <auto-generated />
using System;
using Cigars.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cigars.Migrations
{
    [DbContext(typeof(CigarDataContext))]
    partial class CigarDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.18");

            modelBuilder.Entity("Cigars.Data.Cigar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Binder")
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .HasColumnType("TEXT");

                    b.Property<string>("Filler")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("Wrapper")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("cigar_set", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Binder = "Nicaraguan",
                            Body = "Full",
                            Brand = "Drew Estate",
                            Filler = "Nicaraguan",
                            Name = "Liga Privada No. 9",
                            Origin = "Nicaraguan",
                            Price = 23.989999999999998,
                            Wrapper = "Maduro Nicaraguan"
                        },
                        new
                        {
                            Id = 2,
                            Binder = "Dominican",
                            Body = "Full",
                            Brand = "Arturo Fuente",
                            Filler = "Dominican",
                            Name = "OpusX",
                            Origin = "Dominican",
                            Price = 29.989999999999998,
                            Wrapper = "Maduro Dominican"
                        },
                        new
                        {
                            Id = 3,
                            Binder = "Nicaraguan",
                            Body = "Full",
                            Brand = "Padron",
                            Filler = "Nicaraguan",
                            Name = "1926 Serie",
                            Origin = "Nicaraguan",
                            Price = 34.5,
                            Wrapper = "Natural Nicaraguan"
                        },
                        new
                        {
                            Id = 4,
                            Binder = "Cuban",
                            Body = "Medium-Full",
                            Brand = "Cohiba",
                            Filler = "Cuban",
                            Name = "Behike",
                            Origin = "Cuban",
                            Price = 45.75,
                            Wrapper = "Colorado Cuban"
                        },
                        new
                        {
                            Id = 5,
                            Binder = "Cuban",
                            Body = "Medium",
                            Brand = "Montecristo",
                            Filler = "Cuban",
                            Name = "No. 2",
                            Origin = "Cuban",
                            Price = 22.75,
                            Wrapper = "Maduro Cuban"
                        },
                        new
                        {
                            Id = 6,
                            Binder = "Nicaraguan",
                            Body = "Medium",
                            Brand = "Rocky Patel",
                            Filler = "Nicaraguan",
                            Name = "Vintage 1990",
                            Origin = "Nicaraguan",
                            Price = 18.5,
                            Wrapper = "Sumatra"
                        },
                        new
                        {
                            Id = 7,
                            Binder = "Dominican",
                            Body = "Medium-Full",
                            Brand = "Romeo y Julieta",
                            Filler = "Dominican",
                            Name = "Churchill",
                            Origin = "Dominican",
                            Price = 21.25,
                            Wrapper = "Maduro Dominican"
                        },
                        new
                        {
                            Id = 8,
                            Binder = "Nicaraguan",
                            Body = "Full",
                            Brand = "Oliva",
                            Filler = "Nicaraguan",
                            Name = "Serie V",
                            Origin = "Nicaraguan",
                            Price = 19.989999999999998,
                            Wrapper = "Sun Grown Nicaraguan"
                        },
                        new
                        {
                            Id = 9,
                            Binder = "Dominican",
                            Body = "Full",
                            Brand = "La Flor Dominicana",
                            Filler = "Dominican",
                            Name = "Andalusian Bull",
                            Origin = "Dominican",
                            Price = 28.989999999999998,
                            Wrapper = "Colorado Ecuadorian"
                        },
                        new
                        {
                            Id = 10,
                            Binder = "Nicaraguan",
                            Body = "Full",
                            Brand = "Black Works Studio",
                            Filler = "Nicaraguan",
                            Name = "Killer Bee",
                            Origin = "Nicaraguan",
                            Price = 13.75,
                            Wrapper = "Maduro Ecuadorian"
                        },
                        new
                        {
                            Id = 11,
                            Binder = "Nicaraguan",
                            Body = "Full",
                            Brand = "Black Works Studio",
                            Filler = "Nicaraguan",
                            Name = "NBK",
                            Origin = "Nicaraguan",
                            Price = 14.5,
                            Wrapper = "San Andres Mexican"
                        },
                        new
                        {
                            Id = 12,
                            Binder = "Nicaraguan",
                            Body = "Full",
                            Brand = "Black Label Trading Company",
                            Filler = "Nicaraguan",
                            Name = "Lawless",
                            Origin = "Nicaraguan",
                            Price = 11.75,
                            Wrapper = "Pennsylvania Broadleaf"
                        },
                        new
                        {
                            Id = 13,
                            Binder = "Nicaraguan",
                            Body = "Medium",
                            Brand = "Black Works Studio",
                            Filler = "Nicaraguan",
                            Name = "Green Hornet",
                            Origin = "Nicaraguan",
                            Price = 12.99,
                            Wrapper = "Candela"
                        },
                        new
                        {
                            Id = 14,
                            Binder = "Nicaraguan",
                            Body = "Medium-Full",
                            Brand = "Black Label Trading Company",
                            Filler = "Nicaraguan",
                            Name = "Royalty",
                            Origin = "Nicaraguan",
                            Price = 10.5,
                            Wrapper = "Connecticut Broadleaf"
                        },
                        new
                        {
                            Id = 15,
                            Binder = "Nicaraguan",
                            Body = "Full",
                            Brand = "Black Label Trading Company",
                            Filler = "Nicaraguan",
                            Name = "Bishops Blend",
                            Origin = "Nicaraguan",
                            Price = 11.99,
                            Wrapper = "Maduro Nicaraguan"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
